### ISSUE TITLE
provide ability to convert any key to putty ppk format

### ISSUE THREAD

**Issue by gargamel007** [nickryand/vagrant-multi-putty#21]
Hi. 
Thanks for your plugin it is pretty userful for me as I'm stuck with a Windows Host !
As I sometimes use custom keys on my guests boxes, I'd rather skip the conversion process with puttygen and use a new configuration : `vm.config.putty.raw_private_key_path` and have the plugin generate the compatible .ppk key file.

I have no ruby dev environment nor am I a Ruby Dev, but it could be a simple fix : 

```
private_key = vm.config.putty.private_key_path ||
        get_putty_key(vm.config.putty.raw_private_key_path) ||
        get_putty_key_file(ssh_info[:private_key_path][0])
```

What do you think ?
Thanks :)

**Comment by nickryand** [comment]
you should be able to set `config.ssh.private_key_path` to the path of your custom SSH key and the conversion should kick in automatically. Can you try that out and let me know if it does not work?

**Comment by nickryand** [comment]
Closing this out due to no response.
