### ISSUE TITLE
WinSCP support?

### ISSUE THREAD

**Issue by vitrilo** [nickryand/vagrant-multi-putty#26]
It will be good to have same support for WinSCP as for Putty. Private Keys are same, need just spawn WinSCP process with correct parameters.

The is already exists plugin for scp - https://github.com/invernizzi/vagrant-scp, but it for different purpose - for file copy in command line fashion, not for listing/browsing, as full feature WinSCP UI provide.

**Comment by nickryand** [comment]
@vitrilo I would accept a PR for this. I may have time to get to it at some point but unsure when.

**Comment by nickryand** [comment]
@vitrilo I took a look at the command line arguments for WinSCP. I feel that WinSCP should have its own plugin. The command line arguments are very different from Putty. I think that trying to add support for it to this plugin would be confusing to people.

Good idea though. If I get time in the future, I may try to build one.
