### ISSUE TITLE
Generate the .ppk on vagrant up

### ISSUE THREAD

**Issue by thiagotalma** [nickryand/vagrant-multi-putty#27]
It would be very useful if the conversion of the key was done soon after the creation of the private key, instead of the conversion occurring only when the plugin is executed.

Is it possible to implement this?

Cheers!

**Comment by nickryand** [comment]
I'm sure there could be a way to do this by updating the plugin to execute during the initial `vagrant up`. I would be willing to accept a PR for this but I won't have time to work on it myself.
